# Generated by Django 5.0.4 on 2024-05-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_swap_space_app', '0006_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
