# Generated by Django 5.0.4 on 2024-05-08 18:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_swap_space_app', '0007_remove_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Lokalizacja'),
        ),
    ]
